export const COIN_NAMES: Record<string, string> = {
  BTC: "Bitcoin",
  ETH: "Ethereum",
  BNB: "BNB",
  SOL: "Solana",
  XRP: "XRP",
  DOGE: "Dogecoin",
  ADA: "Cardano",
  AVAX: "Avalanche",
  LINK: "Chainlink",
  DOT: "Polkadot",
  MATIC: "Polygon",
  USDT: "Tether USDt",
  USDC: "USDC",
  SHIB: "Shiba Inu",
  LTC: "Litecoin",
  BCH: "Bitcoin Cash",
  UNI: "Uniswap",
  ATOM: "Cosmos",
  XLM: "Stellar",
  XMR: "Monero",
  ETC: "Ethereum Classic",
  HBAR: "Hedera",
  VET: "VeChain",
  FIL: "Filecoin",
  ICP: "Internet Computer",
  NEAR: "NEAR Protocol",
  AAVE: "Aave",
  ALGO: "Algorand",
  GRT: "The Graph",
  FTM: "Fantom",
  EOS: "EOS",
  SAND: "The Sandbox",
  MANA: "Decentraland",
  THETA: "Theta Network",
  XTZ: "Tezos",
  AXS: "Axie Infinity",
  CHZ: "Chiliz",
  ENJ: "Enjin Coin",
  DASH: "Dash",
  ZEC: "Zcash",
  BAT: "Basic Attention Token",
  CRV: "Curve DAO Token",
  MKR: "Maker",
  COMP: "Compound",
  YFI: "yearn.finance",
  SNX: "Synthetix",
  SUSHI: "SushiSwap",
  RUNE: "THORChain",
  AR: "Arweave",
  KSM: "Kusama",
  EGLD: "MultiversX",
  QNT: "Quant",
  NEO: "Neo",
  RNDR: "Render",
  OP: "Optimism",
  ARB: "Arbitrum",
  APT: "Aptos",
  SUI: "Sui",
  PEPE: "Pepe",
  WLD: "Worldcoin",
  TIA: "Celestia",
  INJ: "Injective",
  FTT: "FTX Token"
};

export function getFullCoinName(baseAsset: string): string {
  return COIN_NAMES[baseAsset] || baseAsset;
}
