ALTER TABLE public.market_symbols ADD COLUMN IF NOT EXISTS name text;

UPDATE public.market_symbols SET name = 'Bitcoin' WHERE symbol = 'BTCUSDT';
UPDATE public.market_symbols SET name = 'Ethereum' WHERE symbol = 'ETHUSDT';
UPDATE public.market_symbols SET name = 'BNB' WHERE symbol = 'BNBUSDT';
UPDATE public.market_symbols SET name = 'Solana' WHERE symbol = 'SOLUSDT';
UPDATE public.market_symbols SET name = 'XRP' WHERE symbol = 'XRPUSDT';
UPDATE public.market_symbols SET name = 'Dogecoin' WHERE symbol = 'DOGEUSDT';
UPDATE public.market_symbols SET name = 'Cardano' WHERE symbol = 'ADAUSDT';
UPDATE public.market_symbols SET name = 'Avalanche' WHERE symbol = 'AVAXUSDT';
UPDATE public.market_symbols SET name = 'Chainlink' WHERE symbol = 'LINKUSDT';
UPDATE public.market_symbols SET name = 'Polkadot' WHERE symbol = 'DOTUSDT';
UPDATE public.market_symbols SET name = 'Polygon' WHERE symbol = 'MATICUSDT';
UPDATE public.market_symbols SET name = 'Tether US' WHERE symbol = 'USDTUSDT';
UPDATE public.market_symbols SET name = 'USDC' WHERE symbol = 'USDCUSDT';
UPDATE public.market_symbols SET name = 'Shiba Inu' WHERE symbol = 'SHIBUSDT';
UPDATE public.market_symbols SET name = 'Litecoin' WHERE symbol = 'LTCUSDT';
UPDATE public.market_symbols SET name = 'Bitcoin Cash' WHERE symbol = 'BCHUSDT';
UPDATE public.market_symbols SET name = 'Uniswap' WHERE symbol = 'UNIUSDT';
UPDATE public.market_symbols SET name = 'Cosmos' WHERE symbol = 'ATOMUSDT';
UPDATE public.market_symbols SET name = 'Stellar' WHERE symbol = 'XLMUSDT';
UPDATE public.market_symbols SET name = 'Monero' WHERE symbol = 'XMRUSDT';
UPDATE public.market_symbols SET name = 'Ethereum Classic' WHERE symbol = 'ETCUSDT';
UPDATE public.market_symbols SET name = 'Hedera' WHERE symbol = 'HBARUSDT';
UPDATE public.market_symbols SET name = 'VeChain' WHERE symbol = 'VETUSDT';
UPDATE public.market_symbols SET name = 'Filecoin' WHERE symbol = 'FILUSDT';
UPDATE public.market_symbols SET name = 'Internet Computer' WHERE symbol = 'ICPUSDT';
UPDATE public.market_symbols SET name = 'NEAR Protocol' WHERE symbol = 'NEARUSDT';
UPDATE public.market_symbols SET name = 'Aave' WHERE symbol = 'AAVEUSDT';
UPDATE public.market_symbols SET name = 'Algorand' WHERE symbol = 'ALGOUSDT';
UPDATE public.market_symbols SET name = 'The Graph' WHERE symbol = 'GRTUSDT';
UPDATE public.market_symbols SET name = 'Fantom' WHERE symbol = 'FTMUSDT';
UPDATE public.market_symbols SET name = 'EOS' WHERE symbol = 'EOSUSDT';
UPDATE public.market_symbols SET name = 'The Sandbox' WHERE symbol = 'SANDUSDT';
UPDATE public.market_symbols SET name = 'Decentraland' WHERE symbol = 'MANAUSDT';
UPDATE public.market_symbols SET name = 'Theta Network' WHERE symbol = 'THETAUSDT';
UPDATE public.market_symbols SET name = 'Tezos' WHERE symbol = 'XTZUSDT';
UPDATE public.market_symbols SET name = 'Axie Infinity' WHERE symbol = 'AXSUSDT';
UPDATE public.market_symbols SET name = 'Chiliz' WHERE symbol = 'CHZUSDT';
UPDATE public.market_symbols SET name = 'Enjin Coin' WHERE symbol = 'ENJUSDT';
UPDATE public.market_symbols SET name = 'Dash' WHERE symbol = 'DASHUSDT';
UPDATE public.market_symbols SET name = 'Zcash' WHERE symbol = 'ZECUSDT';
UPDATE public.market_symbols SET name = 'Basic Attention Token' WHERE symbol = 'BATUSDT';
UPDATE public.market_symbols SET name = 'Curve DAO Token' WHERE symbol = 'CRVUSDT';
UPDATE public.market_symbols SET name = 'Maker' WHERE symbol = 'MKRUSDT';
UPDATE public.market_symbols SET name = 'Compound' WHERE symbol = 'COMPUSDT';
UPDATE public.market_symbols SET name = 'yearn.finance' WHERE symbol = 'YFIUSDT';
UPDATE public.market_symbols SET name = 'Synthetix' WHERE symbol = 'SNXUSDT';
UPDATE public.market_symbols SET name = 'SushiSwap' WHERE symbol = 'SUSHIUSDT';
UPDATE public.market_symbols SET name = 'THORChain' WHERE symbol = 'RUNEUSDT';
UPDATE public.market_symbols SET name = 'Arweave' WHERE symbol = 'ARUSDT';
UPDATE public.market_symbols SET name = 'Kusama' WHERE symbol = 'KSMUSDT';
UPDATE public.market_symbols SET name = 'MultiversX' WHERE symbol = 'EGLDUSDT';
UPDATE public.market_symbols SET name = 'Quant' WHERE symbol = 'QNTUSDT';
UPDATE public.market_symbols SET name = 'Neo' WHERE symbol = 'NEOUSDT';
UPDATE public.market_symbols SET name = 'Render' WHERE symbol = 'RNDRUSDT';
UPDATE public.market_symbols SET name = 'Optimism' WHERE symbol = 'OPUSDT';
UPDATE public.market_symbols SET name = 'Arbitrum' WHERE symbol = 'ARBUSDT';
UPDATE public.market_symbols SET name = 'Aptos' WHERE symbol = 'APTUSDT';
UPDATE public.market_symbols SET name = 'Sui' WHERE symbol = 'SUIUSDT';
UPDATE public.market_symbols SET name = 'Pepe' WHERE symbol = 'PEPEUSDT';
UPDATE public.market_symbols SET name = 'Worldcoin' WHERE symbol = 'WLDUSDT';
UPDATE public.market_symbols SET name = 'Celestia' WHERE symbol = 'TIAUSDT';
UPDATE public.market_symbols SET name = 'Injective' WHERE symbol = 'INJUSDT';
UPDATE public.market_symbols SET name = 'FTX Token' WHERE symbol = 'FTTUSDT';
